#!/usr/bin/perl -w

use strict;
use FileHandle;
use Data::Dumper;
use File::Basename;
use File::Spec;
use Sys::Hostname;
use URI;

my $HOME = (getpwuid ($<))[7];

sub runGitCommand
{
  my @cmd = @_;
  system (@cmd)
    and die ("Command `@cmd' failed");
}

sub getGitHubID
{
  my @cred = do { my $fh = 'FileHandle'->new ("<$HOME/.git-credentials"); die unless ($fh); <$fh> };
  for my $cred (@cred)
    {
      chomp ($cred);
      my $url = 'URI'->new ($cred);
   
      my $host = $url->host; 

      next unless ($host eq 'github.com');
  
      my $userinfo = $url->userinfo;
      
      my ($user, $token) = split(':', $userinfo, 2);
 
      return $user;
    }
}

my $id = &getGitHubID ();

my @remote = split (m/\n/o, `git remote -v`);

if (my $c = $!)
  {
    die;
  }

my %name2location;

for my $remote (@remote)
  {
    my ($name, $location) = split (m/\s+/o, $remote);
    $name2location{$name} = $location;
  }

if ($name2location{origin} && ($name2location{origin} =~ m{^https://github.com/}))
  {
    my $location = $name2location{origin};
    my $depot = &basename ($location); $location = &dirname ($location);
    my $user = &basename ($location); $location = &dirname ($location);
    my $site = &basename ($location);

    if ($user ne $id)
      {
        &runGitCommand ('git', 'remote', 'rename', 'origin', $user);
        &runGitCommand ('git', 'remote', 'add', 'origin', "https://$site/$id/$depot");
      }
  }
elsif ($name2location{origin} && ($name2location{origin} =~ m,^/home/gmap/mrpe/mary/repositories/,o))
  {
    my $location = $name2location{origin};
    my $depot = &basename ($location);
    
    &runGitCommand ('git', 'remote', 'rename', 'origin', 'mary');
    &runGitCommand ('git', 'remote', 'add', 'origin', "https://github.com/$id/$depot");
  }




